version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - ./src:/code/app
      - .env:/code/.env
    ports:
      - 8008:8000
    depends_on:
      - triplestore
      - upload-triplestore
    environment:
      - SPARQL_ENDPOINT=http://triplestore:9999/blazegraph/namespace/kb/sparql
  triplestore:
    image: anitacaron/blazegraph:v0.4
    # command: java -server -Xmx10G -Dcom.bigdata.rdf.sail.webapp.ConfigParams.propertyFile=/RWStore.properties -jar blazegraph.jar
    environment:
      - JAVA_OPTS=-Xmx10G
    ports:
      - 9999:9999
    volumes:
      - ./data:/data
      - ./config/RWStore.properties:/RWStore.properties
      - ./config/log4j.properties:/log4j.properties
    healthcheck:
      test: ["CMD", "curl", "-f", "http://triplestore:9999/"]
      interval: 3s
      timeout: 5s
      retries: 3
  upload-triplestore:
    build:
      context: .
      dockerfile: upload.Dockerfile
    depends_on:
      - triplestore
    links:
      - triplestore
    environment:
      - SERVER=http://triplestore:9999/blazegraph
    volumes:
      - ./data:/data
      - ./config/RWStore.properties:/RWStore.properties