version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - ./src:/code/app
      - .env:/code/.env
    ports:
      - 8008:8000
    depends_on:
      - triplestore
      - upload-triplestore
    environment:
      - SPARQL_ENDPOINT=http://triplestore:8889/bigdata/sparql
  triplestore:
    image: anitacaron/blazegraph:v0.1
    environment:
      - JVM_MEM=10g
    ports:
      - 8889:8080
    volumes:
      - ./data:/data:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://triplestore:8889/"]
      interval: 3s
      timeout: 5s
      retries: 3
  upload-triplestore:
    build:
      context: .
      dockerfile: upload.Dockerfile
    depends_on:
      - triplestore
    links:
      - triplestore
    environment:
      - SERVER=http://triplestore:8889
    volumes:
      - ./data:/data