version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - ./src:/code/app
      - .env:/code/.env
    ports:
      - 8008:8000
    depends_on:
      - triplestore
      - upload-triplestore
    environment:
      - SPARQL_ENDPOINT=http://triplestore:9999/bigdata/sparql
  triplestore:
    image: anitacaron/blazegraph:v0.3.1
    command: java -server -Xmx10g -jar blazegraph.jar
    environment:
      - JAVA_OPTS=-Xmx10G
    ports:
      - 9999:9999
    volumes:
      - ./data:/data:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://triplestore:9999/"]
      interval: 3s
      timeout: 5s
      retries: 3
  upload-triplestore:
    build:
      context: .
      dockerfile: upload.Dockerfile
    depends_on:
      - triplestore
    links:
      - triplestore
    environment:
      - SERVER=http://triplestore:9999/bigdata
    volumes:
      - ./data:/data