#!/usr/bin/env bash
# 
# This script indexes the solr.json which is generated by dumps data pipeline
# Whenever you need to index or re-index your data you can use this script.

while getopts h:p:c: flag
do
    case "${flag}" in
        h) host=${OPTARG};;
        p) port=${OPTARG};;
        c) collection=${OPTARG};;
        *) echo "!!! Invalid flag. Only -h and -p flags are supported."
    esac
done

echo "Indexing $collection in server $host:$port"
curl --location --request POST "http://$host:$port/solr/$collection/update/json?commit=true" --header 'Content-Type: application/json' --data-binary '@mappings.jsonld'

